const puppeteer = require('puppeteer');

const {
    ExpiredDomains
} = require('./lib/ExpiredDomains');
const {
    Mail
} = require('./lib/Mail');

const {
    checkThisDomain
} = require('./lib');


let sourceDomainList = [
    'Alien.cx',
    '360-Event.fr',
    'NickYoungDriving.co.uk',
    'cfecgc67.fr',
    'ars-consilium.fr',
    'optiqueprogress.fr',
    'Bellis.am',
    'StockMoto.fr',
    'Caps.am',
    'KevinMarinProgramAdOr.es',
    'location-veules-les-roses.fr',
    'restaurant-boccaccio.fr',
    'gasch.fr',
    'caliceetcorolle.fr',
    'PropertyManagement.id',
    'guadalturia.es',
    'KidsGarden-Alicante.es',
    'rutasvinovalencia.es',
    'GaliServices.es',
    'Gps.org.es',
    'conisco.es',
    'cdvalldalba.es',
    'sanygas10.es',
    'reverdec.es',
    'kebapenavila.es',
    'concesionarioantoniobravo.es',
    'zajednica-sru-vukovar.hr',
    'oda.hr',
    'ordinacija-martic.hr',
    'cabinet-peltier-avocat.fr',
    'pmp.hr',
    'DelMat-Tours.hr',
    'ebisa.fr',
    'inisia.fr',
    'sauver-son-couple.fr',
    'antimoda.hr',
    'bacic.hr',
    'oka.hr',
    'mros.hr',
    'hrba.hr',
    'RunArte.es',
    'marketiko.eu',
    'AranService.es',
    'escobasdebruja.es',
    'r4shopper.co.uk',
    'BandEraEspanola.es',
    'migoodtel.es',
    'feweb-mathematicscourse.nl',
    'comunidadrc.es',
    'dyjmobiliario.es',
    'integrareclinica.es',
    'paulinoinmobiliaria.es',
    'bminstalaciones.es',
    'restaurantlediapason.fr',
    'elejidoesmiprioridad.es',
    'tandtjek.nu',
    'RamaMetal.es',
    'CodeOranje.nu',
    'knullad.nu',
    'Toyhouse.nu',
    'NomIs.nu',
    'kalaspaket.nu',
    'cykeltjuven.nu',
    'dekwast.nu',
    'trapprenovering.nu',
    'Haircare.nu',
    'idg2c.es',
    'DogSeven.es',
    'centrointegrare.es',
    'centrosintegrare.es',
    'integrareclinicas.es',
    'baloncerco.es',
    'pedrazcabezasdentista.es',
    'FredVision.es',
    'JoyAs-Shop.es',
    'OndaPhone.es',
    'GregorioElias.es',
    'umzuege.tel',
    'buscajob.es',
    'forumcomercial.es',
    'alterqueso.es',
    'China-Clutch.es',
    'CoworkingSalamanca.es',
    'intellimentsecurity.es',
    'clinicasintegrare.es',
    'portalculturalandaluz.es',
    'InternetMadrid.es',
    'uno-consulting.eu',
    'EliasCasaDo.es',
    'paz.nu',
    'centrosrehabilitacion.es',
    'BlubUtterFly.es',
    'netdax.es',
    'cepmenudets.es',
    'PulsarPlay.es',
    'iteciluminacion.es',
    'ceipfedericogarcialorca.es',
    'opigrum.es',
    'escobadebruja.es',
    'CorBatAs-Shop.es',
    'gemeloscamisa-shop.es',
    'cinturones-shop.es',
    'tredzee.es',
    'cheapple.es',
    'remaja.co.id',
    'flatroofersurbiton.co.uk',
    'estilosabroso.es',
    'aceroscorrugados.es',
    'JobcentreContactNumber.co.uk',
    'murcinova.es',
    'MaxHeadroom.nu',
    'DotInfra.tel',
    'szaszet-tiszk.eu',
    'trufo.es',
    'amorevero.es',
    'Tube.com.es',
    'VisualMerchandising.es',
    'ubersetzung.es',
    'Tuscany-Travel.es',
    'talser.es',
    'alagrec.eu',
    '2015.com.es',
    'projektledaren.nu',
    'juegosmil.es',
    'Saver.es',
    'ayuntamientodeillano.es',
    'qadabra.es',
    'proservis.es',
    'PremierMusic.es',
    'SexVote.es',
    'saymor.es',
    'Save4You.es',
    'nummos.es',
    'necronet.es',
    'tme.nu',
    'ofertando.es',
    'nadons.es',
    'Pashmina-Shop.es',
    'OnFocus.es',
    'thermalogica.co.uk',
    'monetbar.es',
    'minuskel.es',
    'mchn.es',
    'MadridStock.es',
    'loteriadiadelpadre.es',
    'loteriadiadelosenamorados.es',
    'loshoyosportugalete.es',
    'microimplantes.es',
    'lashou.es',
    'lacuevapintada.es',
    'l-carnitina.es',
    'juegos1000.es',
    'TheNorthFaceCheap.co.uk',
    'websg.eu',
    'dmmdistribution.eu',
    'juliocaminas.es',
    'juegoszaping.es',
    'l-arginina.es',
    'Jigsaw.es',
    'imaglass.es',
    'islajuegos.es',
    'www28456.cc',
    'yolike.tv',
    'maninthearena.tv',
    'Friend.tv',
    'Templar.tv',
    'PerfectCoverage.tv',
    'RemindMeLater.cc',
    'Unlike.tv',
    'rse.tv',
    'Reaction.tv',
    'jornalnacional.tv',
    'BetSystem.cc',
    'SpeedKings.tv',
    'hogarverde.es',
    'KitchenWakefield.co.uk',
    'HangzhouWan.cc',
    'shijueyishu.cc',
    'takip.cc',
    'suofeier.cc',
    'explora.cc',
    '820yy.cc',
    'Garbage.cc',
    'premasaakshi.tv',
    'Malawi.cc',
    'PrivateEquity.cc',
    'Andrei.tv',
    'vutune.tv',
    'Affiliated.cc',
    'xiaobb.cc',
    'newhopebc.tv',
    'UppsalaStudent.tv',
    'toryumedia.tv',
    'yupin.tv',
    'ooknow.tv',
    'FreeSyria.tv',
    'Sunrooms.tv',
    'Approval.cc',
    'Elections.cc',
    'intim-city.cc',


];


(async () => {

    /*  let sourceDomainList = await new ExpiredDomains().fetch();
     if (!sourceDomainList.length) return;
  */
    const browser = await puppeteer.launch();
    let checkList = [];
    let checkCnt = 0;


    for (let i = 0, len = sourceDomainList.length; i < len; i++) {

        let domain = sourceDomainList[i];

        checkThisDomain(browser, domain)
            .then(async (data) => {
                checkCnt++;
                if (data.shouldInCheckList) checkList.push(data);
                if (checkCnt === len) {
                    await browser.close();
                    if (!checkList.length) return;
                    (new Mail()).send(checkList);
                }
            });
    }
})();